### ISSUE TITLE
when ever I click lastFm stats on any song it only shows info about a particular song

### ISSUE THREAD

**Issue by Tetrax-10** [LucasBares/spicetify-last-fm#4]

**Comment by Taeko-ar** [comment]
The extension shows the last song scrobbled on last.fm, I'll change it to use the Spicetify API to get the songs

**Comment by Tetrax-10** [comment]
Hi
How did you get your Last.FM API Key, did you just create a application with your API account.
Did you pay any money for quota

**Comment by Taeko-ar** [comment]
> Hi How did you get your Last.FM API Key, did you just create a application with your API account. Did you pay any money for quota

Yeah, you can create an app [here](https://www.last.fm/api/account/create) and use that api key.
And no, it doesn't charge anything for it. Not sure if its bc I'm a Pro user on their website or if they doesn't charge at all for the api usage.
